# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RaftMessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RaftMessages.proto',
  package='Raft',
  syntax='proto3',
  serialized_pb=_b('\n\x12RaftMessages.proto\x12\x04Raft\"h\n\x0bRequestVote\x12\x10\n\x08\x66romNode\x18\x01 \x03(\t\x12\x0e\n\x06toNode\x18\x02 \x03(\t\x12\x0c\n\x04term\x18\x03 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x04 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x05 \x01(\x05\"M\n\nVoteResult\x12\x10\n\x08\x66romNode\x18\x01 \x03(\t\x12\x0e\n\x06toNode\x18\x02 \x03(\t\x12\x0c\n\x04term\x18\x03 \x01(\x05\x12\x0f\n\x07granted\x18\x04 \x01(\x08\"p\n\x0eWrapperMessage\x12\x1f\n\x04type\x18\x01 \x01(\x0e\x32\x11.Raft.MessageType\x12\x1e\n\x03rvm\x18\x02 \x01(\x0b\x32\x11.Raft.RequestVote\x12\x1d\n\x03vrm\x18\x03 \x01(\x0b\x32\x10.Raft.VoteResult*A\n\x0bMessageType\x12\x0f\n\x0bREQUESTVOTE\x10\x00\x12\x0e\n\nVOTERESULT\x10\x01\x12\x11\n\rAPPENDENTRIES\x10\x03\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='Raft.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUESTVOTE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VOTERESULT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='APPENDENTRIES', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=327,
  serialized_end=392,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
REQUESTVOTE = 0
VOTERESULT = 1
APPENDENTRIES = 3



_REQUESTVOTE = _descriptor.Descriptor(
  name='RequestVote',
  full_name='Raft.RequestVote',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromNode', full_name='Raft.RequestVote.fromNode', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toNode', full_name='Raft.RequestVote.toNode', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='term', full_name='Raft.RequestVote.term', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastLogIndex', full_name='Raft.RequestVote.lastLogIndex', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastLogTerm', full_name='Raft.RequestVote.lastLogTerm', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=132,
)


_VOTERESULT = _descriptor.Descriptor(
  name='VoteResult',
  full_name='Raft.VoteResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromNode', full_name='Raft.VoteResult.fromNode', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='toNode', full_name='Raft.VoteResult.toNode', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='term', full_name='Raft.VoteResult.term', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='granted', full_name='Raft.VoteResult.granted', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=211,
)


_WRAPPERMESSAGE = _descriptor.Descriptor(
  name='WrapperMessage',
  full_name='Raft.WrapperMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Raft.WrapperMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rvm', full_name='Raft.WrapperMessage.rvm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vrm', full_name='Raft.WrapperMessage.vrm', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=325,
)

_WRAPPERMESSAGE.fields_by_name['type'].enum_type = _MESSAGETYPE
_WRAPPERMESSAGE.fields_by_name['rvm'].message_type = _REQUESTVOTE
_WRAPPERMESSAGE.fields_by_name['vrm'].message_type = _VOTERESULT
DESCRIPTOR.message_types_by_name['RequestVote'] = _REQUESTVOTE
DESCRIPTOR.message_types_by_name['VoteResult'] = _VOTERESULT
DESCRIPTOR.message_types_by_name['WrapperMessage'] = _WRAPPERMESSAGE
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE

RequestVote = _reflection.GeneratedProtocolMessageType('RequestVote', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTVOTE,
  __module__ = 'RaftMessages_pb2'
  # @@protoc_insertion_point(class_scope:Raft.RequestVote)
  ))
_sym_db.RegisterMessage(RequestVote)

VoteResult = _reflection.GeneratedProtocolMessageType('VoteResult', (_message.Message,), dict(
  DESCRIPTOR = _VOTERESULT,
  __module__ = 'RaftMessages_pb2'
  # @@protoc_insertion_point(class_scope:Raft.VoteResult)
  ))
_sym_db.RegisterMessage(VoteResult)

WrapperMessage = _reflection.GeneratedProtocolMessageType('WrapperMessage', (_message.Message,), dict(
  DESCRIPTOR = _WRAPPERMESSAGE,
  __module__ = 'RaftMessages_pb2'
  # @@protoc_insertion_point(class_scope:Raft.WrapperMessage)
  ))
_sym_db.RegisterMessage(WrapperMessage)


# @@protoc_insertion_point(module_scope)
