# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testmessages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='testmessages.proto',
  package='Raft',
  syntax='proto3',
  serialized_pb=_b('\n\x12testmessages.proto\x12\x04Raft\"B\n\rHeartbeatTest\x12\x10\n\x08\x66romnode\x18\x01 \x01(\t\x12\x0e\n\x06tonode\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HEARTBEATTEST = _descriptor.Descriptor(
  name='HeartbeatTest',
  full_name='Raft.HeartbeatTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fromnode', full_name='Raft.HeartbeatTest.fromnode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tonode', full_name='Raft.HeartbeatTest.tonode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='Raft.HeartbeatTest.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['HeartbeatTest'] = _HEARTBEATTEST

HeartbeatTest = _reflection.GeneratedProtocolMessageType('HeartbeatTest', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATTEST,
  __module__ = 'testmessages_pb2'
  # @@protoc_insertion_point(class_scope:Raft.HeartbeatTest)
  ))
_sym_db.RegisterMessage(HeartbeatTest)


# @@protoc_insertion_point(module_scope)
